version: "2"
run:
  concurrency: 4
linters:
  default: none
  enable:
    - gochecknoinits
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - wrapperFunc
        - hugeParam
        - rangeValCopy
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: should have a package comment, unless it's in another file for this package
      - linters:
          - gocritic
        text: 'exitAfterDefer:'
      - linters:
          - gocritic
        text: 'whyNoLint: include an explanation for nolint directive'
      - linters:
          - govet
        text: go.mongodb.org/mongo-driver/bson/primitive.E
      - linters:
          - gosec
        text: weak cryptographic primitive
      - linters:
          - staticcheck
        text: at least one file in a package should have a package comment
      - linters:
          - revive
        text: 'package-comments: should have a package comment'
      - linters:
          - gosec
        text: Deferring unsafe method "Close" on type "io.ReadCloser"
      - linters:
          - revive
          - unparam
          - unused
        path: _test\.go$
        text: unused-parameter
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
